name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build (no default features)
      run: cargo build --verbose --no-default-features
    - name: Build (default features)
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
